version: '3'

services:
  postgres:
    container_name: postgres
    image: 'postgres:latest'

    ports:
      - 5432:5432

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: testdb
  
  user:
    container_name: user
    image: 'ruedigermueller/user:undertest'
    links: 
      - postgres
    ports:
      - 3000:3000
    environment:
      TYPEORM_CONNECTION: postgres
      TYPEORM_HOST: postgres
      TYPEORM_PORT: 5432
      TYPEORM_USERNAME: postgres
      TYPEORM_PASSWORD: changeme
      TYPEORM_DATABASE: testdb
      TYPEORM_ENTITIES: dist/**/*.entity.js
      TYPEORM_SYNCHRONIZE: true  
      TYPEORM_MIGRATION: migration/*.js
      TYPEORM_LOGGING: true